//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInterface.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SJStarERPEntities : DbContext
    {
        public SJStarERPEntities()
            : base("name=SJStarERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseMaster> CourseMasters { get; set; }
        public virtual DbSet<ptaAddressDetail> ptaAddressDetails { get; set; }
        public virtual DbSet<ptaBoardAndUniversityMaster> ptaBoardAndUniversityMasters { get; set; }
        public virtual DbSet<ptaDeclaration> ptaDeclarations { get; set; }
        public virtual DbSet<ptaEducationDetail> ptaEducationDetails { get; set; }
        public virtual DbSet<ptaEducationSubjectMark> ptaEducationSubjectMarks { get; set; }
        public virtual DbSet<ptaEduEvaluationTypeMaster> ptaEduEvaluationTypeMasters { get; set; }
        public virtual DbSet<ptaGenderMaster> ptaGenderMasters { get; set; }
        public virtual DbSet<ptaGuardian> ptaGuardians { get; set; }
        public virtual DbSet<ptaLeadSourceMaster> ptaLeadSourceMasters { get; set; }
        public virtual DbSet<ptaMedicalStatusMaster> ptaMedicalStatusMasters { get; set; }
        public virtual DbSet<ptaNatioalityMaster> ptaNatioalityMasters { get; set; }
        public virtual DbSet<ptaPassport> ptaPassports { get; set; }
        public virtual DbSet<ptaPilotRegistrationMaster> ptaPilotRegistrationMasters { get; set; }
        public virtual DbSet<ptaRegistrationInfo> ptaRegistrationInfoes { get; set; }
        public virtual DbSet<ptaResultStatusMaster> ptaResultStatusMasters { get; set; }
        public virtual DbSet<ptaStreamMaster> ptaStreamMasters { get; set; }
        public virtual DbSet<ptaTitleMaster> ptaTitleMasters { get; set; }
        public virtual DbSet<ptaUGBoardAndUniversityMaster> ptaUGBoardAndUniversityMasters { get; set; }
        public virtual DbSet<SessionMaster> SessionMasters { get; set; }
        public virtual DbSet<ptaScreeningInfo> ptaScreeningInfoes { get; set; }
        public virtual DbSet<ptaScreeningTestType> ptaScreeningTestTypes { get; set; }
        public virtual DbSet<ptaScreeningTestResult> ptaScreeningTestResults { get; set; }
        public virtual DbSet<ptaScreeningExamFeeInfo> ptaScreeningExamFeeInfoes { get; set; }
        public virtual DbSet<RegistrationMaster> RegistrationMasters { get; set; }
        public virtual DbSet<tblGetTermAcceptancyByCandidate> tblGetTermAcceptancyByCandidates { get; set; }
    }
}
