//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInterface.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaAddressDetail
    {
        public int Id { get; set; }
        public string Cor_Country { get; set; }
        public string Cor_State { get; set; }
        public string Cor_District { get; set; }
        public string Cor_City { get; set; }
        public string Cor_Address1 { get; set; }
        public string Cor_Address2 { get; set; }
        public string Cor_PinCode { get; set; }
        public bool IsPermanent { get; set; }
        public string Per_Country { get; set; }
        public string Per_State { get; set; }
        public string Per_District { get; set; }
        public string Per_City { get; set; }
        public string Per_Address1 { get; set; }
        public string Per_Address2 { get; set; }
        public string Per_PinCode { get; set; }
        public int ptaRegistrationInfoId { get; set; }
    
        public virtual ptaRegistrationInfo ptaRegistrationInfo { get; set; }
    }
}
