//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInterface.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaEducationSubjectMark
    {
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public Nullable<double> MaximumMark { get; set; }
        public Nullable<double> ObtainMark { get; set; }
        public Nullable<double> Percentage { get; set; }
        public int ptaEducationDetailId { get; set; }
    
        public virtual ptaEducationDetail ptaEducationDetail { get; set; }
    }
}
