//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInterface.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaGuardian
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Relation { get; set; }
        public int ptaRegistrationInfoId { get; set; }
    
        public virtual ptaRegistrationInfo ptaRegistrationInfo { get; set; }
    }
}
