//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInterface.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaScreeningExamFeeInfo
    {
        public int Id { get; set; }
        public Nullable<int> PTAScreeningInfoId { get; set; }
        public int ScreeningAmountTerm { get; set; }
        public int ScreeningAmount { get; set; }
        public System.DateTime DateOfAmount { get; set; }
        public string PaymentId { get; set; }
        public string ExamResult { get; set; }
        public Nullable<int> PTAScreeningTestTypeId { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int PTAPilotRegistrationMaterId { get; set; }
    
        public virtual ptaPilotRegistrationMaster ptaPilotRegistrationMaster { get; set; }
        public virtual ptaScreeningInfo ptaScreeningInfo { get; set; }
        public virtual ptaScreeningTestType ptaScreeningTestType { get; set; }
    }
}
