//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationInterface.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGetTermAcceptancyByCandidate
    {
        public int Id { get; set; }
        public int tblPerformanceEntryMasterId { get; set; }
        public Nullable<bool> Accept { get; set; }
        public Nullable<System.DateTime> DateOfAction { get; set; }
    }
}
