//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddmissionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddmissionMaster()
        {
            this.AddmissionDetails = new HashSet<AddmissionDetail>();
            this.AddressDetails = new HashSet<AddressDetail>();
            this.BatchHistoryDetails = new HashSet<BatchHistoryDetail>();
            this.CandidateTerminationResignationInfoes = new HashSet<CandidateTerminationResignationInfo>();
            this.CourseChangeHistoryDetails = new HashSet<CourseChangeHistoryDetail>();
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.ExceededFeeAmountOnCourseChanges = new HashSet<ExceededFeeAmountOnCourseChange>();
            this.FIN_FeeReceiptMaster = new HashSet<FIN_FeeReceiptMaster>();
            this.FIN_FeeRefundMaster = new HashSet<FIN_FeeRefundMaster>();
            this.MedicalDetails = new HashSet<MedicalDetail>();
            this.tblPerformanceEntryMasters = new HashSet<tblPerformanceEntryMaster>();
            this.RefundInformations = new HashSet<RefundInformation>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
        public bool IsAppeared { get; set; }
        public string PassingYear { get; set; }
        public bool IsValidPassport { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> AddmissionDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string ImageUrl { get; set; }
        public int RegistrationNo { get; set; }
        public string AmityEnrollMentId { get; set; }
        public bool IsActive { get; set; }
        public string ResumeUrl { get; set; }
        public string RegisterEmail { get; set; }
        public Nullable<int> RegistrationMasterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddmissionDetail> AddmissionDetails { get; set; }
        public virtual CourseMaster CourseMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual RegistrationMaster RegistrationMaster { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressDetail> AddressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchHistoryDetail> BatchHistoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTerminationResignationInfo> CandidateTerminationResignationInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseChangeHistoryDetail> CourseChangeHistoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceededFeeAmountOnCourseChange> ExceededFeeAmountOnCourseChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_FeeReceiptMaster> FIN_FeeReceiptMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_FeeRefundMaster> FIN_FeeRefundMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalDetail> MedicalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceEntryMaster> tblPerformanceEntryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundInformation> RefundInformations { get; set; }
    }
}
