//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddmissionDetail
    {
        public int Id { get; set; }
        public int AddmissionId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public int SessionId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
        public virtual BatchMaster BatchMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual SessionMaster SessionMaster { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
    }
}
