//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressDetail
    {
        public int Id { get; set; }
        public int AddmissionId { get; set; }
        public string CopAddress { get; set; }
        public string CopState { get; set; }
        public string CopCity { get; set; }
        public string CopZip { get; set; }
        public string PerAddress { get; set; }
        public string PerState { get; set; }
        public string PerCity { get; set; }
        public string PerZip { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
    }
}
