//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAndAmountDetail
    {
        public int Id { get; set; }
        public string DDRTGSNo { get; set; }
        public int PartWisePaymentId { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual PartWisePayment PartWisePayment { get; set; }
    }
}
