//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchHistoryDetail
    {
        public int Id { get; set; }
        public int BatchFromId { get; set; }
        public int BatchToId { get; set; }
        public string Description { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public int AdmissionId { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
        public virtual BatchMaster BatchMaster { get; set; }
        public virtual BatchMaster BatchMaster1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
