//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTRInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateTRInfo()
        {
            this.ScheduledStatusLogForTerminateResignations = new HashSet<ScheduledStatusLogForTerminateResignation>();
        }
    
        public int Id { get; set; }
        public int CandidateTerminationResignationInfoId { get; set; }
        public string StatusInfo { get; set; }
        public Nullable<System.DateTime> SchedulingDate { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string ActionName { get; set; }
        public Nullable<System.DateTime> TerminationOrResignationDate { get; set; }
        public Nullable<int> ResignNoticePeriod { get; set; }
        public bool IsClosed { get; set; }
        public string ClosedComment { get; set; }
    
        public virtual CandidateTerminationResignationInfo CandidateTerminationResignationInfo { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledStatusLogForTerminateResignation> ScheduledStatusLogForTerminateResignations { get; set; }
    }
}
