//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseChangeHistoryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseChangeHistoryDetail()
        {
            this.FeeSettlementOnCourseChnageLogs = new HashSet<FeeSettlementOnCourseChnageLog>();
        }
    
        public int Id { get; set; }
        public int CourseFrom { get; set; }
        public int CourseTo { get; set; }
        public int SessionFrom { get; set; }
        public int SessionTo { get; set; }
        public string Description { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public int RegistrationNo { get; set; }
        public Nullable<int> AdmissionMasterId { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
        public virtual CourseMaster CourseMaster { get; set; }
        public virtual CourseMaster CourseMaster1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual SessionMaster SessionMaster { get; set; }
        public virtual SessionMaster SessionMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeSettlementOnCourseChnageLog> FeeSettlementOnCourseChnageLogs { get; set; }
    }
}
