//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDetail
    {
        public int Id { get; set; }
        public int AddmissionId { get; set; }
        public int DocumentId { get; set; }
        public bool IsSubmmited { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual DocumentMaster DocumentMaster { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
    }
}
