//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeEmailNotifacationLog
    {
        public int Id { get; set; }
        public Nullable<int> RegNo { get; set; }
        public string CourseName { get; set; }
        public string FeeInstallmentName { get; set; }
        public System.DateTime LogDate { get; set; }
        public System.DateTime StartDateOfSendingMail { get; set; }
        public System.DateTime EndDateofSendingMail { get; set; }
        public string CandidateName { get; set; }
        public bool IsSenEmail { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
    }
}
