//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeSettlementOnCourseChnageLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeSettlementOnCourseChnageLog()
        {
            this.FeeDetails = new HashSet<FeeDetail>();
        }
    
        public int Id { get; set; }
        public int CourseChangeHistoryDetailId { get; set; }
        public int FeeDetailFrom { get; set; }
        public int FeeDetailIdTo { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual CourseChangeHistoryDetail CourseChangeHistoryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeDetail> FeeDetails { get; set; }
        public virtual FeeDetail FeeDetail { get; set; }
        public virtual FeeDetail FeeDetail1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
