//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeTypeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeTypeDetail()
        {
            this.FeeDetails = new HashSet<FeeDetail>();
            this.SessionInstallmentMasters = new HashSet<SessionInstallmentMaster>();
        }
    
        public int Id { get; set; }
        public int FeeTypeId { get; set; }
        public int CourseId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsActive { get; set; }
        public int SessionMasterId { get; set; }
    
        public virtual CourseMaster CourseMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeDetail> FeeDetails { get; set; }
        public virtual FeeType FeeType { get; set; }
        public virtual SessionMaster SessionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionInstallmentMaster> SessionInstallmentMasters { get; set; }
    }
}
