//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_FeeReceiptDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIN_FeeReceiptDetail()
        {
            this.FIN_BankDetail = new HashSet<FIN_BankDetail>();
        }
    
        public int Id { get; set; }
        public int EntryId { get; set; }
        public Nullable<int> FeeId { get; set; }
        public string FeeName { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public string FeeRemarks { get; set; }
        public string TransectionId { get; set; }
        public string ModOfPayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_BankDetail> FIN_BankDetail { get; set; }
        public virtual FIN_FeeReceiptMaster FIN_FeeReceiptMaster { get; set; }
    }
}
