//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_FeeRefundDetail
    {
        public int Id { get; set; }
        public int EntryId { get; set; }
        public Nullable<int> FeeId { get; set; }
        public string FeeName { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public string FeeRemarks { get; set; }
    
        public virtual FIN_FeeRefundMaster FIN_FeeRefundMaster { get; set; }
    }
}
