//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalDetail
    {
        public int Id { get; set; }
        public int AddmissionId { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string VisionLeft { get; set; }
        public string VisionRight { get; set; }
        public string MedicalCenter { get; set; }
        public Nullable<System.DateTime> MedicalDate { get; set; }
        public Nullable<System.DateTime> FitnessDate { get; set; }
        public string MedicalStatus { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> DateOfWithdrawn { get; set; }
        public Nullable<int> EnteredBy { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
