//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartWisePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartWisePayment()
        {
            this.BankAndAmountDetails = new HashSet<BankAndAmountDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int FeeCollectionId { get; set; }
        public string RecieptNo { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAndAmountDetail> BankAndAmountDetails { get; set; }
        public virtual FeeCollection FeeCollection { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
    }
}
