//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaBankDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaBankDetail()
        {
            this.ptaFeePaymentDetails = new HashSet<ptaFeePaymentDetail>();
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string BeneficiaryName { get; set; }
        public string BankName { get; set; }
        public string AccountType { get; set; }
        public string BranchAddress { get; set; }
        public string IFSC_Code { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> FIN_FeeReceiptDetailID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaFeePaymentDetail> ptaFeePaymentDetails { get; set; }
    }
}
