//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaDocumentDetail
    {
        public int Id { get; set; }
        public int DocumentMasterId { get; set; }
        public string DocumentPath { get; set; }
        public string Extention { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int ptaPilotRegistrationMasterId { get; set; }
        public Nullable<int> ptaAdmissionMasterId { get; set; }
        public Nullable<int> EnteredStudentBy { get; set; }
        public Nullable<int> UpdatedStudentBy { get; set; }
    
        public virtual DocumentMaster DocumentMaster { get; set; }
        public virtual ptaAdmissionMaster ptaAdmissionMaster { get; set; }
        public virtual ptaStudentLogin ptaStudentLogin { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual ptaPilotRegistrationMaster ptaPilotRegistrationMaster { get; set; }
        public virtual ptaStudentLogin ptaStudentLogin1 { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
    }
}
