//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaEducationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaEducationDetail()
        {
            this.ptaEducationSubjectMarks = new HashSet<ptaEducationSubjectMark>();
        }
    
        public int Id { get; set; }
        public string Class { get; set; }
        public string NameOfInstitute { get; set; }
        public Nullable<int> ptaBoardAndUniversityMasterId { get; set; }
        public Nullable<int> ptaUGBoardAndUniversityMasterId { get; set; }
        public Nullable<int> ptaStreamMasterId { get; set; }
        public Nullable<int> ptaDegreeMasterId { get; set; }
        public string YearOfPassing { get; set; }
        public Nullable<int> ptaEduEvaluationTypeMasterId { get; set; }
        public Nullable<double> PercentageOrCGPA { get; set; }
        public Nullable<int> ptaResultStatusMasterId { get; set; }
        public int ptaRegistrationInfoId { get; set; }
    
        public virtual ptaBoardAndUniversityMaster ptaBoardAndUniversityMaster { get; set; }
        public virtual ptaEduEvaluationTypeMaster ptaEduEvaluationTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaEducationSubjectMark> ptaEducationSubjectMarks { get; set; }
        public virtual ptaRegistrationInfo ptaRegistrationInfo { get; set; }
        public virtual ptaResultStatusMaster ptaResultStatusMaster { get; set; }
        public virtual ptaStreamMaster ptaStreamMaster { get; set; }
        public virtual ptaUGBoardAndUniversityMaster ptaUGBoardAndUniversityMaster { get; set; }
    }
}
