//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaFeeCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaFeeCollection()
        {
            this.ptaPartWisePayments = new HashSet<ptaPartWisePayment>();
        }
    
        public int Id { get; set; }
        public int PTAFeePaymentDetailId { get; set; }
        public string RecieptNo { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string PanNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PTAInstallmentMasterId { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
        public virtual ptaFeePaymentDetail ptaFeePaymentDetail { get; set; }
        public virtual ptaInstallmentMaster ptaInstallmentMaster { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaPartWisePayment> ptaPartWisePayments { get; set; }
    }
}
