//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaPilotRegistrationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaPilotRegistrationMaster()
        {
            this.ptaDocumentDetails = new HashSet<ptaDocumentDetail>();
            this.ptaRegistrationInfoes = new HashSet<ptaRegistrationInfo>();
            this.ptaScreeningInfoes = new HashSet<ptaScreeningInfo>();
            this.ptaScreeningExamFeeInfoes = new HashSet<ptaScreeningExamFeeInfo>();
            this.ptaScreeningExamfailedLogs = new HashSet<ptaScreeningExamfailedLog>();
            this.ptaScreeningEmailNotificationLogs = new HashSet<ptaScreeningEmailNotificationLog>();
        }
    
        public int Id { get; set; }
        public int RegistrationNo { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<double> Height { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int CourseId { get; set; }
        public int SessionId { get; set; }
        public bool IsActive { get; set; }
        public string SerialNo { get; set; }
        public string OrderId { get; set; }
        public string ApplicationNo { get; set; }
        public int DepartmentMasterId { get; set; }
    
        public virtual CourseMaster CourseMaster { get; set; }
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaDocumentDetail> ptaDocumentDetails { get; set; }
        public virtual SessionMaster SessionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaRegistrationInfo> ptaRegistrationInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningInfo> ptaScreeningInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningExamFeeInfo> ptaScreeningExamFeeInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningExamfailedLog> ptaScreeningExamfailedLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningEmailNotificationLog> ptaScreeningEmailNotificationLogs { get; set; }
    }
}
