//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaPartWisePayment
    {
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int PTAFeeCollectionId { get; set; }
        public string RecieptNo { get; set; }
        public Nullable<int> PTAPaymentModeId { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    
        public virtual ptaFeeCollection ptaFeeCollection { get; set; }
        public virtual ptaPaymentMode ptaPaymentMode { get; set; }
    }
}
