//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaRegistrationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaRegistrationInfo()
        {
            this.ptaAddressDetails = new HashSet<ptaAddressDetail>();
            this.ptaDeclarations = new HashSet<ptaDeclaration>();
            this.ptaEducationDetails = new HashSet<ptaEducationDetail>();
            this.ptaGuardians = new HashSet<ptaGuardian>();
            this.ptaPassports = new HashSet<ptaPassport>();
            this.ptaStudentLogins = new HashSet<ptaStudentLogin>();
        }
    
        public int Id { get; set; }
        public string RegistartionNo { get; set; }
        public int ptaTitleMasterId { get; set; }
        public int ptaGenderMasterId { get; set; }
        public int ptaNatioalityMasterId { get; set; }
        public int ptaLeadSourceMasterId { get; set; }
        public int ptaMedicalStatusMasterId { get; set; }
        public int ptaPilotRegistrationMasterId { get; set; }
        public Nullable<int> AdmissionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaAddressDetail> ptaAddressDetails { get; set; }
        public virtual ptaAdmissionMaster ptaAdmissionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaDeclaration> ptaDeclarations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaEducationDetail> ptaEducationDetails { get; set; }
        public virtual ptaGenderMaster ptaGenderMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaGuardian> ptaGuardians { get; set; }
        public virtual ptaLeadSourceMaster ptaLeadSourceMaster { get; set; }
        public virtual ptaMedicalStatusMaster ptaMedicalStatusMaster { get; set; }
        public virtual ptaNatioalityMaster ptaNatioalityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaPassport> ptaPassports { get; set; }
        public virtual ptaPilotRegistrationMaster ptaPilotRegistrationMaster { get; set; }
        public virtual ptaTitleMaster ptaTitleMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaStudentLogin> ptaStudentLogins { get; set; }
    }
}
