//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaScreeningEmailNotificationLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaScreeningEmailNotificationLog()
        {
            this.ptaEmailNotificationSentContents = new HashSet<ptaEmailNotificationSentContent>();
        }
    
        public int Id { get; set; }
        public int PTAPilotRegistrationMasterId { get; set; }
        public string CandidateName { get; set; }
        public string Email { get; set; }
        public int ExamTermNo { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool IsSendEmail { get; set; }
        public decimal Amount { get; set; }
        public string CourseName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaEmailNotificationSentContent> ptaEmailNotificationSentContents { get; set; }
        public virtual ptaPilotRegistrationMaster ptaPilotRegistrationMaster { get; set; }
    }
}
