//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaScreeningTestResult
    {
        public int Id { get; set; }
        public int PTAScreeningInfoId { get; set; }
        public int PTAScreeningTestTypeId { get; set; }
        public double ObtainMark { get; set; }
        public Nullable<bool> IsPassed { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ptaScreeningInfo ptaScreeningInfo { get; set; }
        public virtual ptaScreeningTestType ptaScreeningTestType { get; set; }
    }
}
