//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaScreeningEmailNotificationLog
    {
        public int Id { get; set; }
        public int PTAPilotRegistrationMasterId { get; set; }
        public string CandidateName { get; set; }
        public string Email { get; set; }
        public int ExamTermNo { get; set; }
        public System.DateTime LogDate { get; set; }
        public bool IsSendEmail { get; set; }
        public decimal Amount { get; set; }
        public string CourseName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ptaPilotRegistrationMaster ptaPilotRegistrationMaster { get; set; }
    }
}
