//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptaStudentLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ptaStudentLogin()
        {
            this.ptaDocumentDetails = new HashSet<ptaDocumentDetail>();
            this.ptaDocumentDetails1 = new HashSet<ptaDocumentDetail>();
        }
    
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string ApplicationNo { get; set; }
        public int ptaRegistrationInfoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaDocumentDetail> ptaDocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaDocumentDetail> ptaDocumentDetails1 { get; set; }
        public virtual ptaRegistrationInfo ptaRegistrationInfo { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Role Role { get; set; }
    }
}
