//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundInformation
    {
        public int Id { get; set; }
        public Nullable<int> ExceededFeeAmountOnCourseChangeId { get; set; }
        public decimal RefundAmount { get; set; }
        public bool CaseClosed { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string StatusLine { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public Nullable<int> AddmissionMasterId { get; set; }
    
        public virtual AddmissionMaster AddmissionMaster { get; set; }
        public virtual ExceededFeeAmountOnCourseChange ExceededFeeAmountOnCourseChange { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
