//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationMaster()
        {
            this.AddmissionMasters = new HashSet<AddmissionMaster>();
            this.FeeDetails = new HashSet<FeeDetail>();
        }
    
        public int Id { get; set; }
        public int RegistartionNo { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string CorrespondenceCity { get; set; }
        public string CorrespondenceState { get; set; }
        public string CorrespondenceZip { get; set; }
        public string PermanentAddress { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentState { get; set; }
        public string PermanentZip { get; set; }
        public bool IsAppeared { get; set; }
        public string PassingYear { get; set; }
        public bool IsPassport { get; set; }
        public string PaymentId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool PaymentStatus { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public bool IsAddmission { get; set; }
        public Nullable<bool> IsMedicalClear { get; set; }
        public Nullable<bool> IsScreenningClear { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Education { get; set; }
        public string ModOfPayment { get; set; }
        public string MedicalRemark { get; set; }
        public bool IsConsultantCandidate { get; set; }
        public Nullable<int> SessionId { get; set; }
        public bool IsStandBy { get; set; }
        public bool IsMedicalStandBy { get; set; }
        public bool IsFeePayStandBy { get; set; }
        public bool IsHRCandidate { get; set; }
        public bool IsActive { get; set; }
        public string SerialNo { get; set; }
        public string OrderId { get; set; }
        public string ApplicationNo { get; set; }
        public bool IsReRegister { get; set; }
        public string SourceOfCandidate { get; set; }
        public string AadharCardNo { get; set; }
        public bool IsAadharCard { get; set; }
        public int DepartmentMasterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddmissionMaster> AddmissionMasters { get; set; }
        public virtual CourseMaster CourseMaster { get; set; }
        public virtual DepartmentMaster DepartmentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeDetail> FeeDetails { get; set; }
        public virtual SessionMaster SessionMaster { get; set; }
    }
}
