//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningParameterOption
    {
        public int Id { get; set; }
        public int ScreeningParameterId { get; set; }
        public bool Good { get; set; }
        public bool Fair { get; set; }
        public bool Poor { get; set; }
        public string Remark { get; set; }
        public int ScreeningTestId { get; set; }
    
        public virtual ScreeningParameter ScreeningParameter { get; set; }
        public virtual ScreeningTest ScreeningTest { get; set; }
    }
}
