//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScreeningTest()
        {
            this.ScreeningInterviewerResults = new HashSet<ScreeningInterviewerResult>();
            this.ScreeningParameterOptions = new HashSet<ScreeningParameterOption>();
        }
    
        public int Id { get; set; }
        public int RegistrationId { get; set; }
        public Nullable<int> TatooOrScarId { get; set; }
        public string FlyingExp { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string EyeSightLeft { get; set; }
        public string EyeSightRight { get; set; }
        public string Interviewer { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> DocumentMasterId { get; set; }
        public System.DateTime ScreeningDate { get; set; }
        public string Remark { get; set; }
    
        public virtual DocumentMaster DocumentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreeningInterviewerResult> ScreeningInterviewerResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScreeningParameterOption> ScreeningParameterOptions { get; set; }
        public virtual TatooOrScar TatooOrScar { get; set; }
    }
}
