//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SJStarERPEntities : DbContext
    {
        public SJStarERPEntities()
            : base("name=SJStarERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddmissionDetail> AddmissionDetails { get; set; }
        public virtual DbSet<AddmissionMaster> AddmissionMasters { get; set; }
        public virtual DbSet<AddressDetail> AddressDetails { get; set; }
        public virtual DbSet<BankAndAmountDetail> BankAndAmountDetails { get; set; }
        public virtual DbSet<BatchHistoryDetail> BatchHistoryDetails { get; set; }
        public virtual DbSet<BatchMaster> BatchMasters { get; set; }
        public virtual DbSet<CallCenterRemark> CallCenterRemarks { get; set; }
        public virtual DbSet<CandidateActionMaster> CandidateActionMasters { get; set; }
        public virtual DbSet<CandidateTerminationResignationInfo> CandidateTerminationResignationInfoes { get; set; }
        public virtual DbSet<CandidateTRInfo> CandidateTRInfoes { get; set; }
        public virtual DbSet<CourseChangeHistoryDetail> CourseChangeHistoryDetails { get; set; }
        public virtual DbSet<CourseMaster> CourseMasters { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<DocumentMaster> DocumentMasters { get; set; }
        public virtual DbSet<ExceededFeeAmountOnCourseChange> ExceededFeeAmountOnCourseChanges { get; set; }
        public virtual DbSet<FeeCollection> FeeCollections { get; set; }
        public virtual DbSet<FeeDetail> FeeDetails { get; set; }
        public virtual DbSet<FeeEmailNotifacationLog> FeeEmailNotifacationLogs { get; set; }
        public virtual DbSet<FeePaymentDetail> FeePaymentDetails { get; set; }
        public virtual DbSet<FeeSettlementOnCourseChnageLog> FeeSettlementOnCourseChnageLogs { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<FeeTypeDetail> FeeTypeDetails { get; set; }
        public virtual DbSet<FIN_BankDetail> FIN_BankDetail { get; set; }
        public virtual DbSet<FIN_FeeReceiptDetail> FIN_FeeReceiptDetail { get; set; }
        public virtual DbSet<FIN_FeeReceiptMaster> FIN_FeeReceiptMaster { get; set; }
        public virtual DbSet<FIN_FeeRefundDetail> FIN_FeeRefundDetail { get; set; }
        public virtual DbSet<FIN_FeeRefundMaster> FIN_FeeRefundMaster { get; set; }
        public virtual DbSet<InstallmentMaster> InstallmentMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<MedicalDetail> MedicalDetails { get; set; }
        public virtual DbSet<PartWisePayment> PartWisePayments { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<ptaAddressDetail> ptaAddressDetails { get; set; }
        public virtual DbSet<ptaAdmissionMaster> ptaAdmissionMasters { get; set; }
        public virtual DbSet<ptaBankAndAmountDetail> ptaBankAndAmountDetails { get; set; }
        public virtual DbSet<ptaBankDetail> ptaBankDetails { get; set; }
        public virtual DbSet<ptaBoardAndUniversityMaster> ptaBoardAndUniversityMasters { get; set; }
        public virtual DbSet<ptaCountryCityInfo> ptaCountryCityInfoes { get; set; }
        public virtual DbSet<ptaDeclaration> ptaDeclarations { get; set; }
        public virtual DbSet<ptaDocumentDetail> ptaDocumentDetails { get; set; }
        public virtual DbSet<ptaEducationDetail> ptaEducationDetails { get; set; }
        public virtual DbSet<ptaEducationSubjectMark> ptaEducationSubjectMarks { get; set; }
        public virtual DbSet<ptaEduEvaluationTypeMaster> ptaEduEvaluationTypeMasters { get; set; }
        public virtual DbSet<ptaFeeCollection> ptaFeeCollections { get; set; }
        public virtual DbSet<ptaFeeDetail> ptaFeeDetails { get; set; }
        public virtual DbSet<ptaFeePaymentDetail> ptaFeePaymentDetails { get; set; }
        public virtual DbSet<ptaFeeType> ptaFeeTypes { get; set; }
        public virtual DbSet<ptaFeeTypeDetail> ptaFeeTypeDetails { get; set; }
        public virtual DbSet<ptaGenderMaster> ptaGenderMasters { get; set; }
        public virtual DbSet<ptaGuardian> ptaGuardians { get; set; }
        public virtual DbSet<ptaInstallmentMaster> ptaInstallmentMasters { get; set; }
        public virtual DbSet<ptaLeadSourceMaster> ptaLeadSourceMasters { get; set; }
        public virtual DbSet<ptaMedicalStatusMaster> ptaMedicalStatusMasters { get; set; }
        public virtual DbSet<ptaNatioalityMaster> ptaNatioalityMasters { get; set; }
        public virtual DbSet<ptaPartWisePayment> ptaPartWisePayments { get; set; }
        public virtual DbSet<ptaPassport> ptaPassports { get; set; }
        public virtual DbSet<ptaPaymentMode> ptaPaymentModes { get; set; }
        public virtual DbSet<ptaPaymentType> ptaPaymentTypes { get; set; }
        public virtual DbSet<ptaPilotRegistrationMaster> ptaPilotRegistrationMasters { get; set; }
        public virtual DbSet<ptaRegistrationInfo> ptaRegistrationInfoes { get; set; }
        public virtual DbSet<ptaResultStatusMaster> ptaResultStatusMasters { get; set; }
        public virtual DbSet<ptaScreeningEmailNotificationLog> ptaScreeningEmailNotificationLogs { get; set; }
        public virtual DbSet<ptaScreeningExamfailedLog> ptaScreeningExamfailedLogs { get; set; }
        public virtual DbSet<ptaScreeningExamFeeInfo> ptaScreeningExamFeeInfoes { get; set; }
        public virtual DbSet<ptaScreeningInfo> ptaScreeningInfoes { get; set; }
        public virtual DbSet<ptaScreeningTestResult> ptaScreeningTestResults { get; set; }
        public virtual DbSet<ptaScreeningTestType> ptaScreeningTestTypes { get; set; }
        public virtual DbSet<ptaStreamMaster> ptaStreamMasters { get; set; }
        public virtual DbSet<ptaStudentLogin> ptaStudentLogins { get; set; }
        public virtual DbSet<ptaTitleMaster> ptaTitleMasters { get; set; }
        public virtual DbSet<ptaUGBoardAndUniversityMaster> ptaUGBoardAndUniversityMasters { get; set; }
        public virtual DbSet<RegistrationMaster> RegistrationMasters { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduledStatusLogForTerminateResignation> ScheduledStatusLogForTerminateResignations { get; set; }
        public virtual DbSet<ScreeningInterviewer> ScreeningInterviewers { get; set; }
        public virtual DbSet<ScreeningInterviewerResult> ScreeningInterviewerResults { get; set; }
        public virtual DbSet<ScreeningParameter> ScreeningParameters { get; set; }
        public virtual DbSet<ScreeningParameterOption> ScreeningParameterOptions { get; set; }
        public virtual DbSet<ScreeningTest> ScreeningTests { get; set; }
        public virtual DbSet<SendingEmailForRejectedCandidate> SendingEmailForRejectedCandidates { get; set; }
        public virtual DbSet<SessionInstallmentMaster> SessionInstallmentMasters { get; set; }
        public virtual DbSet<SessionMaster> SessionMasters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TatooOrScar> TatooOrScars { get; set; }
        public virtual DbSet<tblParameterList> tblParameterLists { get; set; }
        public virtual DbSet<tblParameterType> tblParameterTypes { get; set; }
        public virtual DbSet<tblPerformanceEntryMaster> tblPerformanceEntryMasters { get; set; }
        public virtual DbSet<tblPerformanceMaster> tblPerformanceMasters { get; set; }
        public virtual DbSet<tblPerformanceParameterResultMaster> tblPerformanceParameterResultMasters { get; set; }
        public virtual DbSet<tblPerformanceParameterTypeResultMaster> tblPerformanceParameterTypeResultMasters { get; set; }
        public virtual DbSet<tblPerformancePercentageMaster> tblPerformancePercentageMasters { get; set; }
        public virtual DbSet<tblReviewMaster> tblReviewMasters { get; set; }
        public virtual DbSet<tblWeeklyReviewMaster> tblWeeklyReviewMasters { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
        public virtual DbSet<UserActivityLog> UserActivityLogs { get; set; }
    
        public virtual ObjectResult<Sp_GetPerformancePWithParamRepots_Result> Sp_GetPerformancePWithParamRepots(string batchId, Nullable<long> type)
        {
            var batchIdParameter = batchId != null ?
                new ObjectParameter("BatchId", batchId) :
                new ObjectParameter("BatchId", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetPerformancePWithParamRepots_Result>("Sp_GetPerformancePWithParamRepots", batchIdParameter, typeParameter);
        }
    }
}
