//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParameterList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParameterList()
        {
            this.tblPerformanceParameterResultMasters = new HashSet<tblPerformanceParameterResultMaster>();
        }
    
        public int Id { get; set; }
        public string KeyId { get; set; }
        public int tblParameterTypeId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public string Gender { get; set; }
    
        public virtual tblReviewMaster tblReviewMaster { get; set; }
        public virtual tblParameterType tblParameterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceParameterResultMaster> tblPerformanceParameterResultMasters { get; set; }
    }
}
