//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeklyReviewMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWeeklyReviewMaster()
        {
            this.tblPerformanceEntryMasters = new HashSet<tblPerformanceEntryMaster>();
            this.tblPerformanceEntryMasters1 = new HashSet<tblPerformanceEntryMaster>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int tblReviewMasterId { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceEntryMaster> tblPerformanceEntryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceEntryMaster> tblPerformanceEntryMasters1 { get; set; }
        public virtual tblReviewMaster tblReviewMaster { get; set; }
    }
}
