//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserLogin()
        {
            this.AddmissionDetails = new HashSet<AddmissionDetail>();
            this.AddmissionDetails1 = new HashSet<AddmissionDetail>();
            this.AddmissionMasters = new HashSet<AddmissionMaster>();
            this.AddmissionMasters1 = new HashSet<AddmissionMaster>();
            this.BankAndAmountDetails = new HashSet<BankAndAmountDetail>();
            this.BatchHistoryDetails = new HashSet<BatchHistoryDetail>();
            this.CallCenterRemarks = new HashSet<CallCenterRemark>();
            this.CandidateTRInfoes = new HashSet<CandidateTRInfo>();
            this.CourseChangeHistoryDetails = new HashSet<CourseChangeHistoryDetail>();
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.DocumentDetails1 = new HashSet<DocumentDetail>();
            this.ExceededFeeAmountOnCourseChanges = new HashSet<ExceededFeeAmountOnCourseChange>();
            this.FeeCollections = new HashSet<FeeCollection>();
            this.FeeCollections1 = new HashSet<FeeCollection>();
            this.FeeDetails = new HashSet<FeeDetail>();
            this.FeeDetails1 = new HashSet<FeeDetail>();
            this.FeePaymentDetails = new HashSet<FeePaymentDetail>();
            this.FeePaymentDetails1 = new HashSet<FeePaymentDetail>();
            this.FeeSettlementOnCourseChnageLogs = new HashSet<FeeSettlementOnCourseChnageLog>();
            this.FIN_FeeReceiptMaster = new HashSet<FIN_FeeReceiptMaster>();
            this.FIN_FeeReceiptMaster1 = new HashSet<FIN_FeeReceiptMaster>();
            this.FIN_FeeRefundMaster = new HashSet<FIN_FeeRefundMaster>();
            this.FIN_FeeRefundMaster1 = new HashSet<FIN_FeeRefundMaster>();
            this.MedicalDetails = new HashSet<MedicalDetail>();
            this.PartWisePayments = new HashSet<PartWisePayment>();
            this.ptaAdmissionMasters = new HashSet<ptaAdmissionMaster>();
            this.ptaDocumentDetails = new HashSet<ptaDocumentDetail>();
            this.ptaDocumentDetails1 = new HashSet<ptaDocumentDetail>();
            this.ptaFeeCollections = new HashSet<ptaFeeCollection>();
            this.ptaFeeCollections1 = new HashSet<ptaFeeCollection>();
            this.ptaFeePaymentDetails = new HashSet<ptaFeePaymentDetail>();
            this.ptaFeePaymentDetails1 = new HashSet<ptaFeePaymentDetail>();
            this.ptaScreeningExamfailedLogs = new HashSet<ptaScreeningExamfailedLog>();
            this.ptaScreeningInfoes = new HashSet<ptaScreeningInfo>();
            this.ptaScreeningInfoes1 = new HashSet<ptaScreeningInfo>();
            this.ptaStudentLogins = new HashSet<ptaStudentLogin>();
            this.SessionInstallmentMasters = new HashSet<SessionInstallmentMaster>();
            this.SessionInstallmentMasters1 = new HashSet<SessionInstallmentMaster>();
            this.tblPerformanceEntryMasters = new HashSet<tblPerformanceEntryMaster>();
            this.tblPerformanceParameterResultMasters = new HashSet<tblPerformanceParameterResultMaster>();
            this.tblPerformanceParameterTypeResultMasters = new HashSet<tblPerformanceParameterTypeResultMaster>();
            this.tblPerformancePercentageMasters = new HashSet<tblPerformancePercentageMaster>();
            this.tblPerformancePercentageMasters1 = new HashSet<tblPerformancePercentageMaster>();
            this.UserActivityLogs = new HashSet<UserActivityLog>();
            this.RefundInformations = new HashSet<RefundInformation>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Password { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddmissionDetail> AddmissionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddmissionDetail> AddmissionDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddmissionMaster> AddmissionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddmissionMaster> AddmissionMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAndAmountDetail> BankAndAmountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchHistoryDetail> BatchHistoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallCenterRemark> CallCenterRemarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateTRInfo> CandidateTRInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseChangeHistoryDetail> CourseChangeHistoryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceededFeeAmountOnCourseChange> ExceededFeeAmountOnCourseChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeCollection> FeeCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeCollection> FeeCollections1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeDetail> FeeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeDetail> FeeDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeePaymentDetail> FeePaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeePaymentDetail> FeePaymentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeSettlementOnCourseChnageLog> FeeSettlementOnCourseChnageLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_FeeReceiptMaster> FIN_FeeReceiptMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_FeeReceiptMaster> FIN_FeeReceiptMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_FeeRefundMaster> FIN_FeeRefundMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIN_FeeRefundMaster> FIN_FeeRefundMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalDetail> MedicalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartWisePayment> PartWisePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaAdmissionMaster> ptaAdmissionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaDocumentDetail> ptaDocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaDocumentDetail> ptaDocumentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaFeeCollection> ptaFeeCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaFeeCollection> ptaFeeCollections1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaFeePaymentDetail> ptaFeePaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaFeePaymentDetail> ptaFeePaymentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningExamfailedLog> ptaScreeningExamfailedLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningInfo> ptaScreeningInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaScreeningInfo> ptaScreeningInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ptaStudentLogin> ptaStudentLogins { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionInstallmentMaster> SessionInstallmentMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionInstallmentMaster> SessionInstallmentMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceEntryMaster> tblPerformanceEntryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceParameterResultMaster> tblPerformanceParameterResultMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformanceParameterTypeResultMaster> tblPerformanceParameterTypeResultMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformancePercentageMaster> tblPerformancePercentageMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPerformancePercentageMaster> tblPerformancePercentageMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserActivityLog> UserActivityLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundInformation> RefundInformations { get; set; }
    }
}
